name: Docker push to Hub
on:
  push:
    branches: [newbranch]
  pull_request:
    branches: [newbranch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build 
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: coolwhiteguy/githubtest
          dockerfile: ../
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
