name: Docker push to Hub
on:
  push:
    branches: [newbranch]
  pull_request:
    branches: [newbranch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and run
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
            image: coolwhiteguy/githubtest
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
